### ISSUE TITLE
V2.0.3 Syncing

### ISSUE THREAD

**Issue by DoomeD1982** [Roeshambo/MonolithDKP#151] opened 2019-12-08 00:36 UTC
I have migrated the dkp tables to 2.0.3, mine all show correctly, I had 1 other player install new version, it wiped his tables, and resynced.

I have 125 players in my list, his is only showing 79 players, and some players have negative numbers. I have had him wipe the tables again, and resynced with the same results.

**Comment by Roeshambo** [comment] 2019-12-08 00:42
can you post your saved variables file here please

**Comment by DoomeD1982** [comment] 2019-12-08 00:47
[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3935730/MonolithDKP.lua.txt)
It didnt seem to like me upload a .lua file, so i added a .txt to the end of it.

**Comment by Roeshambo** [comment] 2019-12-08 00:58
Have one of your players that is not receiving all entries turn on script error reporting (/console scriptErrors1) and start a sync. If they get any errors please post them here.

**Comment by DoomeD1982** [comment] 2019-12-08 01:10
i had 2 users do the console and resync, neither received errors

**Comment by Roeshambo** [comment] 2019-12-08 01:13
Are both of them showing a green indicator? Also have both of them type the following command:
`/script print(MonDKP_Meta.Loot.Havyn.current); print(MonDKP_Meta.DKP.Havyn.current)`

**Comment by DoomeD1982** [comment] 2019-12-08 01:20
ME: 54,19
Player1 54, 19
Player2 54,  19

**Comment by Roeshambo** [comment] 2019-12-08 01:28
Ok. So as far as them only having 79 players. They only populate players that have received DKP in the history. So if the player isn't on the list, they haven't received an entry that has that player in it. As far as the improper values go, were you using 2.0.0 or 2.0.1 prior to this release?

**Comment by Roeshambo** [comment] 2019-12-08 01:29
Also, please post the saved variables file you used to migrate (the one before the migration occurred) if you have that backed up.

**Comment by DoomeD1982** [comment] 2019-12-08 01:29
we did upgrade to 2.0.0 had issues, so we rolled back, i thought correctly. as of yesterday we were running 1.6.3

**Comment by DoomeD1982** [comment] 2019-12-08 01:31
[MonolithDKP-PRE-MIGRATE.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3935757/MonolithDKP-PRE-MIGRATE.lua.txt)

**Comment by Roeshambo** [comment] 2019-12-08 01:33
Ok I think I see your issue. The premigration file already has entries indexed. You're duplicating indexes which is why they're not being sent. One moment.

**Comment by Roeshambo** [comment] 2019-12-08 01:41
Use the below file, change to just .lua. And redo the migration with that. Make sure everyone else wipes their tables

[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3935761/MonolithDKP.lua.txt)

**Comment by DoomeD1982** [comment] 2019-12-08 01:41
so delete gm note as well ?

**Comment by Roeshambo** [comment] 2019-12-08 01:58
Yes you'll need to delete the GM note to do the migration process.

**Comment by DoomeD1982** [comment] 2019-12-08 02:00
I have migrated the data, the 2 players i asked earlier are now not responding of course.
another officer and the GM came online, officer had mentioned no profiles loaded, i redid the sync button, and then his was updated.

so i think everything is working now, just i have 125 in my list and other officers have 96. is there a way to sync everything with officers, or just have to wait for one of those players to get a dkp, and if the other officers are in a raid and im not, they would have to add them to the dkp addon ?

**Comment by Roeshambo** [comment] 2019-12-08 02:04
Yes they can add those players manually to their list if they like. The way the new system works, no profiles are actually transferred in order to minimize data transfers. They are simply created as needed. You *could* hypothetically award them 1 DKP and then delete that entry. That would create entries with those players names in them and create profiles. Glad it was a localized issue.

**Comment by DoomeD1982** [comment] 2019-12-08 02:07
the last issue i guess, and probably not causing an issue, but when syncing, it lists the officers it syncing to twice, including me. 
![image](https://user-images.githubusercontent.com/58643765/70383070-61465780-191c-11ea-9412-c39fe8f6ba43.png)

**Comment by Roeshambo** [comment] 2019-12-08 02:17
Ya, That's because officers are queried twice during the sync process (first officers sync with each other, then the initiating officer pushes to all other players). I just reuploaded 2.0.3 with some niche bug fixes that have been identified that only adds a player to the list if they aren't already on it.

**Comment by DoomeD1982** [comment] 2019-12-08 02:19
so that means tamlin is syncing to me, and im syncing to tamlin ?

**Comment by Roeshambo** [comment] 2019-12-08 02:21
Yes. If he has entries that you do not, he sends them to you so that when you sync the rest of the guild you have all possible entries to send rather than having all officers push their data which can cause disconnects (flooding addon channels is a big no no)

**Comment by Roeshambo** [comment] 2019-12-08 02:25
With regards to officers, seeing their name doesn't necessarily mean you're sending or receiving data to/from them. Officers always respond in sync requests no matter what so they're almost always appear on the list if they're online (only exception is if they recently sync'd. There's a 60 second cooldown on syncing). Non-officers only respond IF their meta tables differ from yours. Thus initiating a broadcast for what it is they're missing.

**Comment by mado299** [comment] 2019-12-08 02:47
we missing Broadcast DKP Table, Broadcast loot History and Broadcast DKP History

**Comment by DoomeD1982** [comment] 2019-12-08 02:48
the system syncs when it needs to now, so those arent needed anymore

**Comment by mado299** [comment] 2019-12-08 02:51
one guy have 135 dkp i give him 10 and other officers only see 135

**Comment by Roeshambo** [comment] 2019-12-08 02:52
If you updated to 2.0.3, all other players must be on that version. It can not talk to older versions by design.

**Comment by DoomeD1982** [comment] 2019-12-08 02:52
and everyone is using 2.0.3, have them click the green circle it should resync

**Comment by mado299** [comment] 2019-12-08 02:55
ok ty

**Closed as completed** 2019-12-08 03:27 UTC
